# Generated by Django 5.1.7 on 2025-04-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_id_alter_customer_id_alter_orderplaced_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('mumbai', 'Maharashtra'), ('Gujrat', 'Gujrat'), ('Kerala', ' Kerala')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HO', 'Hair Oil'), ('HS', 'Hair Serum'), ('HM', 'Hair Mask'), ('HC', 'Hair Conditioner'), ('SH', 'Shampoo'), ('HB', 'Hair Butter'), ('HD', 'Hair Dye'), ('HT', 'Hair Treatment')], max_length=2, null=True),
        ),
    ]
