# Generated by Django 5.1.7 on 2025-04-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_product_composition_remove_product_prodapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('mumbai', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Kerala', ' Kerala')], max_length=100),
        ),
    ]
