# Generated by Django 5.2 on 2025-04-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
